// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU-6mBSwxysPsbJFZGnBKF0rKvupHHrCw',
    appId: '1:851489715751:web:0ebd90a352264b64c3c002',
    messagingSenderId: '851489715751',
    projectId: 'safyan-tariq-7b397',
    authDomain: 'safyan-tariq-7b397.firebaseapp.com',
    storageBucket: 'safyan-tariq-7b397.appspot.com',
    measurementId: 'G-48KVD7SWP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMbSoe-jp43tHZBw_qRVFcbVN7vZG-DHk',
    appId: '1:851489715751:android:1fd1f4f15251e236c3c002',
    messagingSenderId: '851489715751',
    projectId: 'safyan-tariq-7b397',
    storageBucket: 'safyan-tariq-7b397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNpEszaebFxzGDw3hwDSfF1zvf0GR0pFY',
    appId: '1:851489715751:ios:35aa0e30f9b9e515c3c002',
    messagingSenderId: '851489715751',
    projectId: 'safyan-tariq-7b397',
    storageBucket: 'safyan-tariq-7b397.appspot.com',
    iosClientId: '851489715751-m6snipr09sk3tj4h29rfi82vlrb9c79c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNpEszaebFxzGDw3hwDSfF1zvf0GR0pFY',
    appId: '1:851489715751:ios:35aa0e30f9b9e515c3c002',
    messagingSenderId: '851489715751',
    projectId: 'safyan-tariq-7b397',
    storageBucket: 'safyan-tariq-7b397.appspot.com',
    iosClientId: '851489715751-m6snipr09sk3tj4h29rfi82vlrb9c79c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sss',
  );
}
